### PR TITLE
Check attrs for entities

### PR DESCRIPTION
**Pull request by ksmadsen**
Hi,

This branch checks attributes in tags for entity related problems.

It is on top of my earlier branch, and fixes issue #21.

Let me know if there are any issues with this, or if you want me to change something.

Thanks in advance.

### CODE REVIEW

**Comment by petdance** [comment]
Thanks, I will try to see if I can look at this in the next couple of days.

**Comment by ksmadsen** [comment]
FYI, I've updated this pull-request so that it applies cleanly to the newest master.

**Comment by petdance** [comment]
I'm going to release 2.26 and then I'll take a look at this.  I need to have a stable release before I go looking at this.

**Comment by petdance** [comment]
I've merged this manually into dev at 3109a9f.  I'll test it out at work on my work system against work data and see how it turns out.  Thanks.

**Comment by petdance** [comment]
This works marvelously.  I'm cleaning up errors in my work code base that I hadn't even seen before.  Thanks for the submission.

**Pull request closed without merging**
