### PR TITLE
fix tests failing on cpan testers reports

### PR DESCRIPTION
**Pull request by lharey**
Hi

As per my email re the cpan pull request challenge.

This should hopefully fix the failing tests on cpan testers - http://www.cpantesters.org/distro/H/HTML-Lint.html

example fail -
http://www.cpantesters.org/cpan/report/a38f9f44-3d6f-11e5-a615-fd3ac5fc1a82

Cheers
Lisa

### CODE REVIEW

**Comment by petdance** [comment]
What is the bug in the original code that this fixes?  It's not clear to me from the patch.

**Comment by lharey** [comment]
If you have a look at the example test failure t/12-html_fragment_ok.t was failing 
#   Failed test 'Error matches string'
#   at t/LintTest.pl line 36.
#          got: 'Set #1 (6:1) <title> tag is required'
#     expected: 'Set #1 (6:1) <head> tag is required'

I think its actually a bug in the 'tests' and not in the actually module.

LintTest.pl always expects the array order of @expected and @linesets to match
I could have amended the order in t/12-html_fragment_ok.t but thought that the test would be better written to not rely on the array orders.

Does this seem the right thing to do?

**Comment by lharey** [comment]
Hi

The t/12-html-fragment_ok.t seems to be failing - see
http://www.cpantesters.org/cpan/report/a38f9f44-3d6f-11e5-a615-fd3ac5fc1a82

I think its a bug in the test and not the actual module.

LintTest.pl in that it expects the order of the arrays @expected and
@linesets to always match.

I've amended the test so that it doesn't rely on the order of the arrays to
be the same

Does this seem like the right thing to do?

Regards
Lisa

**Comment by petdance** [comment]
I'm wondering why we're even comparing the array ourselves when things like is_deeply() exist.  I would think we could do something like:

    is_deeply( [sort @errors], [sort @expected] );

**Comment by lharey** [comment]
Hi

I've had a look to see if thats possible, but the two arrays are not in the
same formats. @errors are objects and @expected can also include regular
expressions.

Regards
Lisa

**Comment by petdance** [comment]
This has been fixed by another pull request that I got to first.  Thanks for your help.  See 0389052.

**Pull request closed without merging**
